format_version: v1.0
type: GroupComponent
attributes: {displayName: APPLICATION LAYER, id: APPLICATION LAYER}
children:
- type: ElementPosition
  attributes: {x: '17', y: '17', id: APPLICATION LAYER}
