package:
  format-version: "1.0.0"
  name: "bootloader_apps_ethernet"
  version: "v3.4.2"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "bootloader"
      type: "package"
      version: "v3.8.0"
    - name: "FreeRTOS-Kernel"
      type: "package"
      version: "V11.1.0"
