format_version: v1.0
type: GroupComponent
attributes: {displayName: APPLICATION LAYER, id: APPLICATION LAYER}
children:
- type: ElementPosition
  attributes: {x: '16', y: '21', id: APPLICATION LAYER}
