format_version: v1.0
type: GroupComponent
attributes: {displayName: TCP/IP STACK, id: TCP/IP STACK}
children:
- type: ElementPosition
  attributes: {x: '303', y: '218', id: TCP/IP STACK}
- type: Attachments
  children:
  - type: Attachment
    attributes: {namespace: BASIC CONFIGURATION, id: 'tcpipStack:Core_SysConsole_Dependency'}
  - type: Attachment
    attributes: {namespace: BASIC CONFIGURATION, id: 'tcpipStack:Core_SysConsole_Dependency'}
